swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Punditpub API - Main Server'
  description: "Server for dispatching requests between other servers"
host: 'localhost:3000'
basePath: '/'
schemes:
  - 'http'

paths:
  /competitions/getCompetitions:
    get:
      summary: Get all competitions
      parameters:
        - name: filter
          in: query
          description: Filter competitions based on a query parameter
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/CompetitionList'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

  /competitions/getCompetitionById:
    get:
      summary: Get competition by ID
      parameters:
        - name: competitionId
          in: query
          description: ID of the competition to retrieve
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Competition'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

  /competitions/getCompetitionsByCountry:
    get:
      summary: Get competitions by country
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/CompetitionList'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

  /games/getGames:
    get:
      summary: Get all games
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/GameList'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

  /games/clubGamesById/{clubId}:
    get:
      summary: Get games by club ID
      parameters:
        - name: clubId
          in: path
          description: ID of the club to retrieve games
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/GameList'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'


  /player/getPlayersByClub:
    get:
      summary: 'Get Player By Team'
      description: 'Retrieve players based on team filter.'
      parameters:
        - name: 'filter'
          in: 'query'
          required: true
          type: 'string'
      responses:
        '200':
          description: 'List of players for the specified team filter.'
          schema:
            type: array
            items:
              $ref: '#/definitions/Player'
        '500':
          description: 'Internal Server Error'

  /player/getPlayers:
    get:
      summary: 'Get All Players'
      description: 'Retrieve a list of all players.'
      responses:
        '200':
          description: 'List of all players.'
          schema:
            type: array
            items:
              $ref: '#/definitions/Player'
        '500':
          description: 'Internal Server Error'

  /player/getPlayerById:
    get:
      summary: 'Get Player By Player ID'
      description: 'Retrieve player information based on player ID.'
      parameters:
        - name: 'filter'
          in: 'query'
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Player information for the specified player ID.'
          schema:
            $ref: '#/definitions/Player'
        '500':
          description: 'Internal Server Error'

  /player/getAppearancesByPlayerId/{player_id}:
    get:
      summary: Get player appearances by player ID
      parameters:
        - name: player_id
          in: path
          description: ID of the player to retrieve appearances
          required: true
          type: string
        - name: filter
          in: query
          description: Filter appearances based on a query parameter
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Appearance'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

  /player/getAppearancesByGameId/{game_id}:
    get:
      summary: Get player appearances by game ID
      parameters:
        - name: game_id
          in: path
          description: ID of the game to retrieve player appearances
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Appearance'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

  /single-game/getGameEventsById/{game_id}:
    get:
      summary: Get events of a game by ID
      parameters:
        - name: game_id
          in: path
          description: ID of the game to retrieve events
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/GameEvents'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

  /single-game/getGameById/{game_id}:
    get:
      summary: Get details of a game by ID
      parameters:
        - name: game_id
          in: path
          description: ID of the game to retrieve details
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Game'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

  /single-team/getClubById/{clubId}:
    get:
      summary: 'Get Team By ID'
      description: 'Retrieve information about a specific team using its club ID.'
      parameters:
        - name: 'clubId'
          in: 'path'
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Team information for the specified club ID.'
          schema:
            $ref: '#/definitions/Club'
        '500':
          description: 'Internal Server Error'
          schema:
            type: string
          headers:
            Content-Type:
              type: string
              default: 'text/html'


  /teams/getClubsByCompetitions:
    get:
      summary: 'Get Teams By Competition'
      description: 'Retrieve teams based on competition filter.'
      parameters:
        - name: 'filterCompetition'
          in: 'query'
          required: true
          type: 'string'
      responses:
        '200':
          description: 'List of teams for the specified competition.'
          schema:
            type: array
            items:
              $ref: '#/definitions/Club'
        '500':
          description: 'Internal Server Error'

  /teams/clubsBySeasonAndCountry:
    get:
      summary: 'Get Teams By Season and Country'
      description: 'Retrieve teams based on country and season filters.'
      parameters:
        - name: 'filterCountry'
          in: 'query'
          required: true
          type: 'string'
        - name: 'filterSeason'
          in: 'query'
          required: true
          type: 'string'
      responses:
        '200':
          description: 'List of teams for the specified country and season.'
          schema:
            type: array
            items:
              $ref: '#/definitions/Club'
        '500':
          description: 'Internal Server Error'

  /teams/getClubsCountry:
    get:
      summary: 'Get All Team Countries'
      description: 'Retrieve a list of all team countries.'
      responses:
        '200':
          description: 'List of all team countries.'
          schema:
            type: array
            items:
              type: string
        '500':
          description: 'Internal Server Error'

  /teams/getClubSeason:
    get:
      summary: 'Get All Club Seasons'
      description: 'Retrieve a list of all club seasons.'
      responses:
        '200':
          description: 'List of all club seasons.'
          schema:
            type: array
            items:
              type: string
        '500':
          description: 'Internal Server Error'


definitions:
  Competition:
    type: object
    properties:
      competitionId:
        type: string
      competitionCode:
        type: string
      name:
        type: string
      subType:
        type: string
      type:
        type: string
      countryId:
        type: integer
      countryName:
        type: string
      domesticLeagueCode:
        type: string
      confederation:
        type: string
      url:
        type: string

  CompetitionList:
    type: array
    items:
      $ref: '#/definitions/Competition'

  Game:
    type: object
    properties:
      game_id:
        type: number
      competition_id:
        type: string
      season:
        type: number
      round:
        type: string
      date:
        type: string
        format: date
      home_club_id:
        type: number
      away_club_id:
        type: number
      home_club_goals:
        type: number
      away_club_goals:
        type: number
      home_club_position:
        type: number
      away_club_position:
        type: number
      home_club_manager_name:
        type: string
      away_club_manager_name:
        type: string
      stadium:
        type: string
      attendance:
        type: number
      referee:
        type: string
      url:
        type: string
      home_club_name:
        type: string
      away_club_name:
        type: string
      aggregate:
        type: string
      competition_type:
        type: string

  GameList:
    type: array
    items:
      $ref: '#/definitions/Game'


  Player:
    type: object
    properties:
      playerId:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      name:
        type: string
      lastSeason:
        type: integer
      currentClubId:
        type: integer
      playerCode:
        type: string
      countryOfBirth:
        type: string
      cityOfBirth:
        type: string
      countryOfCitizenship:
        type: string
      dateOfBirth:
        type: string
        format: date
      subPosition:
        type: string
      position:
        type: string
      foot:
        type: string
      heightInCm:
        type: integer
      marketValueInEur:
        type: number
      highestMarketValueInEur:
        type: number
      contractExpirationDate:
        type: string
        format: date
      agentName:
        type: string
      imageUrl:
        type: string
      url:
        type: string
      currentClubDomesticCompetitionId:
        type: string
      currentClubName:
        type: string

  GameEvents:
    type: object
    properties:
      _id:
        type: string
        description: Unique identifier for the game event
      game_event_id:
        type: string
        description: Unique game event identifier
      date:
        type: string
        format: date-time
        description: Date and time when the game event occurred
      game_id:
        type: number
        description: Identifier of the game associated with this event
      minute:
        type: number
        description: The minute in the game when the event occurred
      type:
        type: string
        description: Type of the game event (e.g., Cards, Goals, etc.)
      club_id:
        type: number
        description: Identifier of the club associated with this event
      player_id:
        type: number
        description: Identifier of the player involved in this event
      description:
        type: string
        description: Detailed description of the event (e.g., type of card, goal method)

  Club:
    type: object
    properties:
      clubId:
        type: integer
      clubCode:
        type: string
      name:
        type: string
      domesticCompetitionId:
        type: string
      totalMarketValue:
        type: number
        format: double
      squadSize:
        type: integer
      averageAge:
        type: number
        format: double
      foreignersNumber:
        type: integer
      foreignersPercentage:
        type: number
        format: double
      nationalTeamPlayers:
        type: integer
      stadiumName:
        type: string
      stadiumSeats:
        type: integer
      netTransferRecord:
        type: string
      coachName:
        type: string
      lastSeason:
        type: integer
      url:
        type: string

  Appearance:
    type: object
    properties:
      _id:
        type: string
      appearance_id:
        type: string
      game_id:
        type: integer
      player_id:
        type: integer
      player_club_id:
        type: integer
      player_current_club_id:
        type: integer
      date:
        type: string
        format: date-time
      player_name:
        type: string
      competition_id:
        type: string
      yellow_cards:
        type: integer
      red_cards:
        type: integer
      goals:
        type: integer
      assists:
        type: integer
      minutes_played:
        type: integer



  Error:
    type: object
    properties:
      error:
        type: string